<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>erzawinutility.ico</ApplicationIcon>
    <Version>1.0.7</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Erza_PowerPlan.pow" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="erzawinutility.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Erza_PowerPlan.pow" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core\" />
    <Folder Include="Helpers\" />
  </ItemGroup>

</Project>
